### ISSUE TITLE
Unused argument in Shiny App

### ISSUE THREAD

**Issue by ddlawton** [johanWallgren/iMessage#1]
Hey Johan.

I tried to use your code to look at some of my iMessages and ran into an error. I followed your directions up until where you instruct to run the following code:

`library(shiny)
runApp('MessApp')`

when I try to run the app I get the following error:

> Listening on http://127.0.0.1:5145
> Warning: package ‘tidyverse’ was built under R version 3.3.3
> -- Attaching packages ------------------------------------------------------------------- tidyverse 1.2.1 --
> v ggplot2 2.2.1     v purrr   0.2.4
> v tibble  1.4.1     v dplyr   0.7.4
> v tidyr   0.7.2     v stringr 1.2.0
> v readr   1.1.1     v forcats 0.2.0
> Warning: package ‘ggplot2’ was built under R version 3.3.3
> Warning: package ‘tibble’ was built under R version 3.3.3
> Warning: package ‘tidyr’ was built under R version 3.3.3
> Warning: package ‘readr’ was built under R version 3.3.3
> Warning: package ‘purrr’ was built under R version 3.3.3
> Warning: package ‘dplyr’ was built under R version 3.3.3
> Warning: package ‘forcats’ was built under R version 3.3.3
> -- Conflicts ---------------------------------------------------------------------- tidyverse_conflicts() --
> x dplyr::filter() masks stats::filter()
> x dplyr::lag()    masks stats::lag()
> Warning: package ‘tidytext’ was built under R version 3.3.3
> Warning: package ‘tm’ was built under R version 3.3.3
> Loading required package: NLP
> Warning: package ‘NLP’ was built under R version 3.3.3
> 
> Attaching package: ‘NLP’
> 
> The following object is masked from ‘package:ggplot2’:
> 
>     annotate
> 
> Warning: package ‘wordcloud’ was built under R version 3.3.3
> Loading required package: RColorBrewer
> Warning: package ‘shinythemes’ was built under R version 3.3.3
> Warning: Error in checkboxGroupInput: unused arguments (choiceNames = list(phoneOwner, contact), choiceValues = list(phoneOwner, contact))
> Stack trace (innermost first):
>     55: checkboxGroupInput
>     54: tag
>     53: tags$form
>     52: tag
>     51: tags$div
>     50: div
>     49: sidebarPanel
>     48: sidebarLayout
>     47: tag
>     46: tags$div
>     45: div
>     44: tagList
>     43: attachDependencies
>     42: bootstrapPage
>     41: fluidPage
>      1: runApp
> Error : unused
> > Listening on http://127.0.0.1:5145
> Warning: package ‘tidyverse’ was built under R version 3.3.3
> -- Attaching packages ------------------------------------------------------------------- tidyverse 1.2.1 --
> v ggplot2 2.2.1     v purrr   0.2.4
> v tibble  1.4.1     v dplyr   0.7.4
> v tidyr   0.7.2     v stringr 1.2.0
> v readr   1.1.1     v forcats 0.2.0
> Warning: package ‘ggplot2’ was built under R version 3.3.3
> Warning: package ‘tibble’ was built under R version 3.3.3
> Warning: package ‘tidyr’ was built under R version 3.3.3
> Warning: package ‘readr’ was built under R version 3.3.3
> Warning: package ‘purrr’ was built under R version 3.3.3
> Warning: package ‘dplyr’ was built under R version 3.3.3
> Warning: package ‘forcats’ was built under R version 3.3.3
> -- Conflicts ---------------------------------------------------------------------- tidyverse_conflicts() --
> x dplyr::filter() masks stats::filter()
> x dplyr::lag()    masks stats::lag()
> Warning: package ‘tidytext’ was built under R version 3.3.3
> Warning: package ‘tm’ was built under R version 3.3.3
> Loading required package: NLP
> Warning: package ‘NLP’ was built under R version 3.3.3
> 
> Attaching package: ‘NLP’
> 
> The following object is masked from ‘package:ggplot2’:
> 
>     annotate
> 
> Warning: package ‘wordcloud’ was built under R version 3.3.3
> Loading required package: RColorBrewer
> Warning: package ‘shinythemes’ was built under R version 3.3.3
> Warning: Error in checkboxGroupInput: unused arguments (choiceNames = list(phoneOwner, contact), choiceValues = list(phoneOwner, contact))
> Stack trace (innermost first):
>     55: checkboxGroupInput
>     54: tag
>     53: tags$form
>     52: tag
>     51: tags$div
>     50: div
>     49: sidebarPanel
>     48: sidebarLayout
>     47: tag
>     46: tags$div
>     45: div
>     44: tagList
>     43: attachDependencies
>     42: bootstrapPage
>     41: fluidPage
>      1: runApp
> Error : unused arguments (choiceNames = list(phoneOwner, contact), choiceValues = list(phoneOwner, contact))

Can you help solve this issue?

Thanks!

**Comment by johanWallgren** [comment]
Hi.
Thanks for trying my app!
I downloaded all my code and ran it in a new folder and it did not produce an error.
Did you click "clone or download" button to get the code or did you copy the scripts?
If you ran the code as it is in my gitHub and got that error the only thing I can think of is that you need to update your R version, this will also stop all the warnings you get before the error.

**Comment by johanWallgren** [comment]
The error you get is common when there is a parentheses missing somewhere.
Did you edit the code in any way?

**Comment by ddlawton** [comment]
Hey, So I think the problem was I needed to update R. It ran perfectly on 3.5!

Its a good program!

**Comment by johanWallgren** [comment]
Awesome!
